org: fe23devs
service: bonzai-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::024848481193:role/BasicLambdaRole

functions:
  ## Auth
  RegisterUser:
    handler: functions/auth/RegisterUser/index.handler
    events:
      - httpApi:
          path: /api/auth/register
          method: POST
  LoginUser:
    handler: functions/auth/LoginUser/index.handler
    events:
      - httpApi:
          path: /api/auth/login
          method: POST
  ## Bookings
  BookRoom:
    handler: functions/bookings/BookRoom/index.handler
    events:
      - httpApi:
          path: /api/bookings
          method: POST
  UpdateBooking:
    handler: functions/bookings/UpdateBooking/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: PUT
  UpdateBookingStatus:
    handler: functions/bookings/UpdateBookingStatus/index.handler
    events:
      - httpApi:
          path: /api/bookings/{id}
          method: PATCH
  GetBookings:
    handler: functions/bookings/GetBookings/index.handler
    events:
      - httpApi:
          path: /api/bookings
          method: GET
  ## Rooms
  GetRooms:
    handler: functions/rooms/GetRooms/index.handler
    events:
      - httpApi:
          path: /api/rooms
          method: GET

resources:
  Resources:
    BonzaiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bonzai-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
